[vcs]
software = "Git"

[modules.root]
path = "."
packageManager = "Cargo"
main = true

[modules.root.hooks.after_rel]
build = ["cargo", "build"]
test = ["cargo", "test"]

[modules.nodejs]
path = "./nodejs"
packageManager = "Npm"