[package]
name = "panrelease"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
git2 = "0.15.0"

serde = {version = "1.0.149", features = ["derive"]}
toml = "0.5.9"