[package]
name = "panrelease"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
git2 = "0.15.0"
semver = "1.0.14"

serde = {version = "1.0.149", features = ["derive"]}
toml = "0.5.9"
toml_edit = "0.15.0"
