name: npm-release

on:
  push:
    tags: ["*.*.*"]

jobs:
  wasm-rel:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --verbose

      - name: Install dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          mkdir dist
          mkdir builds
      - name: Build WASM32
        run: ./build.sh
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - name: Yarn build
        working-directory: ./nodejs
        run: yarn --frozen-lockfile
      - name: Npm release
        working-directory: ./nodejs
        run: npm publish
